version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/templates/example_hello_world"
    update_schedule: "live"
    default_reviewers:
      - "mnmkng"
  - package_manager: "javascript"
    directory: "/templates/project_playwright_crawler"
    update_schedule: "live"
    default_reviewers:
      - "mnmkng"
  - package_manager: "javascript"
    directory: "/templates/example_puppeteer_single_page"
    update_schedule: "live"
    default_reviewers:
      - "mnmkng"
  - package_manager: "javascript"
    directory: "/templates/project_cheerio_crawler"
    update_schedule: "live"
    default_reviewers:
      - "mnmkng"
  - package_manager: "javascript"
    directory: "/templates/project_empty"
    update_schedule: "live"
    default_reviewers:
      - "mnmkng"
  - package_manager: "javascript"
    directory: "/templates/project_puppeteer_crawler"
    update_schedule: "live"
    default_reviewers:
      - "mnmkng"

