version: 1
update_configs:
    - package_manager: "javascript"
      directory: "/templates/apify_project"
      update_schedule: "live"
      default_reviewers:
         - "drobnikj"
    - package_manager: "javascript"
      directory: "/templates/basic_crawler"
      update_schedule: "live"
      default_reviewers:
        - "drobnikj"
    - package_manager: "javascript"
      directory: "/templates/cheerio_crawler"
      update_schedule: "live"
      default_reviewers:
          - "drobnikj"
    - package_manager: "javascript"
      directory: "/templates/hello_world"
      update_schedule: "live"
      default_reviewers:
          - "drobnikj"
    - package_manager: "javascript"
      directory: "/templates/puppeteer_crawler"
      update_schedule: "live"
      default_reviewers:
          - "drobnikj"
    - package_manager: "javascript"
      directory: "/templates/puppeteer_single_page"
      update_schedule: "live"
      default_reviewers:
          - "drobnikj"
